CREATE TABLE knowledge_bases (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', visibility TEXT NOT NULL CHECK (visibility IN ('public','authenticated','volunteer','learner')), status TEXT NOT NULL CHECK (status IN ('enabled','disabled')), created_by_user_id TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- statement-break
CREATE TABLE knowledge_items (id TEXT PRIMARY KEY, knowledge_base_id TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE RESTRICT, title TEXT NOT NULL, summary TEXT NOT NULL DEFAULT '', content TEXT NOT NULL, category TEXT NOT NULL DEFAULT '', category_id TEXT NULL, keywords_json TEXT NOT NULL DEFAULT '[]', metadata_json TEXT NOT NULL DEFAULT '{}', source_name TEXT NOT NULL, source_url TEXT NULL, visibility TEXT NOT NULL CHECK (visibility IN ('public','authenticated','volunteer','learner')), status TEXT NOT NULL CHECK (status IN ('draft','submitted','reviewed','published','withdrawn','rejected')), effective_at TEXT NOT NULL, withdrawn_at TEXT NULL, previous_version_id TEXT NULL REFERENCES knowledge_items(id) ON DELETE RESTRICT, version INTEGER NOT NULL CHECK (version >= 1), content_hash TEXT NOT NULL, embedding_json TEXT NULL, embedding_model TEXT NULL, embedding_dimension INTEGER NULL, embedding_status TEXT NOT NULL DEFAULT 'none', embedding_generated_at TEXT NULL, embedding_content_hash TEXT NULL, created_by_user_id TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(knowledge_base_id, content_hash));
-- statement-break
CREATE INDEX idx_knowledge_items_retrieval ON knowledge_items(knowledge_base_id, status, visibility, effective_at);
-- statement-break
CREATE TABLE knowledge_images (id TEXT PRIMARY KEY, knowledge_item_id TEXT NOT NULL REFERENCES knowledge_items(id) ON DELETE CASCADE, storage_path TEXT NOT NULL UNIQUE, mime_type TEXT NOT NULL, width INTEGER NULL CHECK (width IS NULL OR width > 0), height INTEGER NULL CHECK (height IS NULL OR height > 0), metadata_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
-- statement-break
CREATE INDEX idx_knowledge_images_item ON knowledge_images(knowledge_item_id);
-- statement-break
CREATE TABLE knowledge_import_batches (id TEXT PRIMARY KEY, knowledge_base_id TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE RESTRICT, file_name TEXT NOT NULL, status TEXT NOT NULL CHECK (status IN ('previewed','confirmed','failed','cancelled')), total_rows INTEGER NOT NULL CHECK (total_rows >= 0), valid_rows INTEGER NOT NULL CHECK (valid_rows >= 0), invalid_rows INTEGER NOT NULL CHECK (invalid_rows >= 0), created_by_user_id TEXT NOT NULL, confirmed_by_user_id TEXT NULL, created_at TEXT NOT NULL, confirmed_at TEXT NULL, updated_at TEXT NOT NULL);
-- statement-break
CREATE TABLE knowledge_import_rows (id TEXT PRIMARY KEY, batch_id TEXT NOT NULL REFERENCES knowledge_import_batches(id) ON DELETE CASCADE, row_number INTEGER NOT NULL CHECK (row_number > 0), raw_data_json TEXT NOT NULL, normalized_data_json TEXT NOT NULL, status TEXT NOT NULL CHECK (status IN ('valid','invalid','imported','duplicate')), error_message TEXT NULL, knowledge_item_id TEXT NULL REFERENCES knowledge_items(id) ON DELETE SET NULL, created_at TEXT NOT NULL, UNIQUE(batch_id, row_number));
-- statement-break
INSERT INTO knowledge_bases (id, name, description, visibility, status, created_by_user_id, created_at, updated_at) SELECT 'learning-materials', 'Learning materials', 'Migrated learning resources', 'learner', 'enabled', 'system', datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM knowledge_bases WHERE id = 'learning-materials');
-- statement-break
INSERT INTO knowledge_items (id, knowledge_base_id, title, summary, content, category, category_id, keywords_json, metadata_json, source_name, source_url, visibility, status, effective_at, withdrawn_at, previous_version_id, version, content_hash, embedding_status, created_by_user_id, created_at, updated_at) SELECT id, 'learning-materials', title, summary, content, resource_type, category_id, tags_json, '{}', source_name, source_url, visibility, CASE status WHEN 'published' THEN 'published' WHEN 'withdrawn' THEN 'withdrawn' ELSE 'submitted' END, effective_at, withdrawn_at, previous_version_id, version, lower(hex(randomblob(16))), 'none', 'system', created_at, updated_at FROM learning_resources;
-- statement-break
ALTER TABLE learning_questions ADD COLUMN source_knowledge_item_id TEXT NULL REFERENCES knowledge_items(id) ON DELETE RESTRICT;
-- statement-break
UPDATE learning_questions SET source_knowledge_item_id = source_resource_id;
