CREATE TABLE learning_resources (id VARCHAR(36) PRIMARY KEY, title TEXT NOT NULL, summary TEXT NOT NULL, content TEXT NOT NULL, resource_type VARCHAR(32) NOT NULL, tags_json TEXT NOT NULL, source_name TEXT NOT NULL, source_url TEXT NULL, version INT NOT NULL, visibility VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, effective_at VARCHAR(40) NOT NULL, withdrawn_at VARCHAR(40) NULL, created_at VARCHAR(40) NOT NULL, updated_at VARCHAR(40) NOT NULL, CONSTRAINT chk_learning_resources_type CHECK (resource_type IN ('team_intro', 'manual', 'prevention', 'case_study')), CONSTRAINT chk_learning_resources_version CHECK (version >= 1), CONSTRAINT chk_learning_resources_visibility CHECK (visibility IN ('public', 'authenticated', 'volunteer', 'learner')), CONSTRAINT chk_learning_resources_status CHECK (status IN ('published', 'withdrawn')));
-- statement-break
CREATE INDEX idx_learning_resources_visible ON learning_resources(status, visibility, effective_at);
-- statement-break
CREATE TABLE learning_questions (id VARCHAR(36) PRIMARY KEY, source_resource_id VARCHAR(36) NOT NULL, prompt TEXT NOT NULL, question_type VARCHAR(32) NOT NULL, difficulty VARCHAR(32) NOT NULL, tags_json TEXT NOT NULL, options_json TEXT NOT NULL, correct_option_id VARCHAR(128) NOT NULL, explanation TEXT NOT NULL, version INT NOT NULL, visibility VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, effective_at VARCHAR(40) NOT NULL, withdrawn_at VARCHAR(40) NULL, created_at VARCHAR(40) NOT NULL, updated_at VARCHAR(40) NOT NULL, CONSTRAINT chk_learning_questions_type CHECK (question_type IN ('single_choice', 'true_false', 'scenario')), CONSTRAINT chk_learning_questions_difficulty CHECK (difficulty IN ('basic', 'intermediate', 'advanced')), CONSTRAINT chk_learning_questions_version CHECK (version >= 1), CONSTRAINT chk_learning_questions_visibility CHECK (visibility IN ('authenticated', 'volunteer', 'learner')), CONSTRAINT chk_learning_questions_status CHECK (status IN ('published', 'withdrawn')), FOREIGN KEY (source_resource_id) REFERENCES learning_resources(id) ON DELETE RESTRICT);
-- statement-break
CREATE INDEX idx_learning_questions_visible ON learning_questions(status, visibility, difficulty, effective_at);
-- statement-break
CREATE TABLE learning_question_answers (id VARCHAR(36) PRIMARY KEY, question_id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL, selected_option_id VARCHAR(128) NOT NULL, is_correct BOOLEAN NOT NULL, question_version INT NOT NULL, created_at VARCHAR(40) NOT NULL, CONSTRAINT chk_learning_question_answers_version CHECK (question_version >= 1), FOREIGN KEY (question_id) REFERENCES learning_questions(id) ON DELETE RESTRICT, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT);
-- statement-break
CREATE INDEX idx_learning_question_answers_user_created ON learning_question_answers(user_id, created_at);
