CREATE TABLE collaboration_spaces (id VARCHAR(64) PRIMARY KEY, case_id VARCHAR(64) NOT NULL, name TEXT NOT NULL, status VARCHAR(16) NOT NULL, created_by_user_id VARCHAR(64) NOT NULL, created_at VARCHAR(40) NOT NULL, archived_at VARCHAR(40) NULL, next_event_version INTEGER NOT NULL DEFAULT 0, CONSTRAINT fk_collaboration_spaces_case FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE, CONSTRAINT fk_collaboration_spaces_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id), CONSTRAINT chk_collaboration_spaces_status CHECK (status IN ('active','archived')), CONSTRAINT chk_collaboration_spaces_version CHECK (next_event_version >= 0));
-- statement-break
CREATE INDEX idx_collaboration_spaces_case_status ON collaboration_spaces(case_id, status, created_at);
-- statement-break
CREATE TABLE space_members (id VARCHAR(64) PRIMARY KEY, space_id VARCHAR(64) NOT NULL, user_id VARCHAR(64) NOT NULL, role VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL, joined_at VARCHAR(40) NOT NULL, left_at VARCHAR(40) NULL, UNIQUE KEY uq_space_members_space_user(space_id, user_id), CONSTRAINT fk_space_members_space FOREIGN KEY (space_id) REFERENCES collaboration_spaces(id) ON DELETE CASCADE, CONSTRAINT fk_space_members_user FOREIGN KEY (user_id) REFERENCES users(id), CONSTRAINT chk_space_members_role CHECK (role IN ('commander','volunteer')), CONSTRAINT chk_space_members_status CHECK (status IN ('active','left')));
-- statement-break
CREATE INDEX idx_space_members_user_status ON space_members(user_id, status);
-- statement-break
CREATE TABLE space_member_slots (user_id VARCHAR(64) NOT NULL, slot INTEGER NOT NULL, member_id VARCHAR(64) NOT NULL UNIQUE, PRIMARY KEY(user_id, slot), CONSTRAINT fk_space_member_slots_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_space_member_slots_member FOREIGN KEY (member_id) REFERENCES space_members(id) ON DELETE CASCADE, CONSTRAINT chk_space_member_slots_slot CHECK (slot BETWEEN 1 AND 3));
-- statement-break
CREATE TABLE space_location_consents (id VARCHAR(64) PRIMARY KEY, space_id VARCHAR(64) NOT NULL, user_id VARCHAR(64) NOT NULL, member_id VARCHAR(64) NOT NULL UNIQUE, consent_version VARCHAR(64) NOT NULL, granted_at VARCHAR(40) NOT NULL, revoked_at VARCHAR(40) NULL, UNIQUE KEY uq_space_location_consents_space_user(space_id, user_id), CONSTRAINT fk_space_location_consents_space FOREIGN KEY (space_id) REFERENCES collaboration_spaces(id) ON DELETE CASCADE, CONSTRAINT fk_space_location_consents_user FOREIGN KEY (user_id) REFERENCES users(id), CONSTRAINT fk_space_location_consents_member FOREIGN KEY (member_id) REFERENCES space_members(id) ON DELETE CASCADE);
-- statement-break
CREATE TABLE space_events (id VARCHAR(64) PRIMARY KEY, space_id VARCHAR(64) NOT NULL, case_id VARCHAR(64) NOT NULL, event_type VARCHAR(96) NOT NULL, version INTEGER NOT NULL, visibility_scope VARCHAR(32) NOT NULL, payload_json LONGTEXT NOT NULL, occurred_at VARCHAR(40) NOT NULL, UNIQUE KEY uq_space_events_space_version(space_id, version), CONSTRAINT fk_space_events_space FOREIGN KEY (space_id) REFERENCES collaboration_spaces(id) ON DELETE CASCADE, CONSTRAINT fk_space_events_case FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE, CONSTRAINT chk_space_events_version CHECK (version > 0), CONSTRAINT chk_space_events_visibility CHECK (visibility_scope IN ('space_members','commanders','self')));
-- statement-break
CREATE INDEX idx_space_events_space_version ON space_events(space_id, version);
-- statement-break
CREATE TABLE event_outbox (id VARCHAR(64) PRIMARY KEY, event_id VARCHAR(64) NOT NULL UNIQUE, topic VARCHAR(96) NOT NULL, status VARCHAR(16) NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0, available_at VARCHAR(40) NOT NULL, delivered_at VARCHAR(40) NULL, created_at VARCHAR(40) NOT NULL, CONSTRAINT fk_event_outbox_event FOREIGN KEY (event_id) REFERENCES space_events(id) ON DELETE CASCADE, CONSTRAINT chk_event_outbox_status CHECK (status IN ('pending','delivered','failed')), CONSTRAINT chk_event_outbox_attempts CHECK (attempt_count >= 0));
-- statement-break
CREATE INDEX idx_event_outbox_pending ON event_outbox(status, available_at);
