CREATE TABLE space_location_samples (id VARCHAR(191) PRIMARY KEY, space_id VARCHAR(191) NOT NULL, user_id VARCHAR(191) NOT NULL, latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, accuracy_meters DOUBLE NOT NULL, captured_at VARCHAR(64) NOT NULL, operation_id VARCHAR(191) NOT NULL UNIQUE, created_at VARCHAR(64) NOT NULL, CONSTRAINT fk_location_space FOREIGN KEY (space_id) REFERENCES collaboration_spaces(id) ON DELETE CASCADE, CONSTRAINT fk_location_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT chk_location_lat CHECK (latitude BETWEEN -90 AND 90), CONSTRAINT chk_location_lng CHECK (longitude BETWEEN -180 AND 180), CONSTRAINT chk_location_accuracy CHECK (accuracy_meters >= 0));
-- statement-break
CREATE INDEX idx_space_location_samples_window ON space_location_samples(space_id, user_id, captured_at);
-- statement-break
CREATE TABLE space_arrivals (id VARCHAR(191) PRIMARY KEY, space_id VARCHAR(191) NOT NULL, user_id VARCHAR(191) NOT NULL, target_type VARCHAR(32) NOT NULL, target_id VARCHAR(191) NOT NULL, arrived_at VARCHAR(64) NOT NULL, accuracy_meters DOUBLE NOT NULL, CONSTRAINT fk_arrival_space FOREIGN KEY (space_id) REFERENCES collaboration_spaces(id) ON DELETE CASCADE, CONSTRAINT fk_arrival_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT chk_arrival_type CHECK (target_type IN ('task','rally_point','area')), CONSTRAINT chk_arrival_accuracy CHECK (accuracy_meters >= 0), UNIQUE KEY uq_space_arrival (space_id, user_id, target_type, target_id));
-- statement-break
CREATE TABLE space_messages (id VARCHAR(191) PRIMARY KEY, space_id VARCHAR(191) NOT NULL, sender_id VARCHAR(191) NOT NULL, message_type VARCHAR(32) NOT NULL, content TEXT NOT NULL, sent_at VARCHAR(64) NOT NULL, recalled_at VARCHAR(64) NULL, CONSTRAINT fk_message_space FOREIGN KEY (space_id) REFERENCES collaboration_spaces(id) ON DELETE CASCADE, CONSTRAINT fk_message_sender FOREIGN KEY (sender_id) REFERENCES users(id), CONSTRAINT chk_message_type CHECK (message_type IN ('text','broadcast')));
-- statement-break
CREATE INDEX idx_space_messages_space_sent ON space_messages(space_id, sent_at);
-- statement-break
CREATE TABLE voice_reports (id VARCHAR(191) PRIMARY KEY, space_id VARCHAR(191) NOT NULL, case_id VARCHAR(191) NOT NULL, reporter_id VARCHAR(191) NOT NULL, object_key VARCHAR(255) NOT NULL UNIQUE, content_type VARCHAR(128) NOT NULL, byte_size BIGINT NOT NULL, status VARCHAR(32) NOT NULL, created_at VARCHAR(64) NOT NULL, failed_reason TEXT NULL, CONSTRAINT fk_voice_space FOREIGN KEY (space_id) REFERENCES collaboration_spaces(id) ON DELETE CASCADE, CONSTRAINT fk_voice_case FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE, CONSTRAINT fk_voice_reporter FOREIGN KEY (reporter_id) REFERENCES users(id), CONSTRAINT chk_voice_size CHECK (byte_size > 0), CONSTRAINT chk_voice_status CHECK (status IN ('uploaded','transcribing','transcribed','draft_ready','failed','reviewed')));
-- statement-break
CREATE TABLE voice_transcripts (id VARCHAR(191) PRIMARY KEY, voice_report_id VARCHAR(191) NOT NULL UNIQUE, content TEXT NOT NULL, provider VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, created_at VARCHAR(64) NOT NULL, CONSTRAINT fk_transcript_report FOREIGN KEY (voice_report_id) REFERENCES voice_reports(id) ON DELETE CASCADE, CONSTRAINT chk_transcript_status CHECK (status IN ('completed','failed')));
