CREATE TABLE knowledge_bases (id VARCHAR(191) PRIMARY KEY, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, visibility VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, created_by_user_id VARCHAR(191) NOT NULL, created_at VARCHAR(64) NOT NULL, updated_at VARCHAR(64) NOT NULL, CONSTRAINT chk_knowledge_base_visibility CHECK (visibility IN ('public','authenticated','volunteer','learner')), CONSTRAINT chk_knowledge_base_status CHECK (status IN ('enabled','disabled')));
-- statement-break
CREATE TABLE knowledge_items (id VARCHAR(191) PRIMARY KEY, knowledge_base_id VARCHAR(191) NOT NULL, title VARCHAR(255) NOT NULL, summary TEXT NOT NULL, content TEXT NOT NULL, category VARCHAR(191) NOT NULL, category_id VARCHAR(191) NULL, keywords_json JSON NOT NULL, metadata_json JSON NOT NULL, source_name VARCHAR(255) NOT NULL, source_url TEXT NULL, visibility VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, effective_at VARCHAR(64) NOT NULL, withdrawn_at VARCHAR(64) NULL, previous_version_id VARCHAR(191) NULL, version INTEGER NOT NULL, content_hash VARCHAR(128) NOT NULL, embedding_json JSON NULL, embedding_model VARCHAR(191) NULL, embedding_dimension INTEGER NULL, embedding_status VARCHAR(32) NOT NULL DEFAULT 'none', embedding_generated_at VARCHAR(64) NULL, embedding_content_hash VARCHAR(128) NULL, created_by_user_id VARCHAR(191) NOT NULL, created_at VARCHAR(64) NOT NULL, updated_at VARCHAR(64) NOT NULL, CONSTRAINT fk_knowledge_item_base FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id), CONSTRAINT fk_knowledge_item_previous FOREIGN KEY (previous_version_id) REFERENCES knowledge_items(id), CONSTRAINT uq_knowledge_item_hash UNIQUE (knowledge_base_id, content_hash), CONSTRAINT chk_knowledge_item_visibility CHECK (visibility IN ('public','authenticated','volunteer','learner')), CONSTRAINT chk_knowledge_item_status CHECK (status IN ('draft','submitted','reviewed','published','withdrawn','rejected')), CONSTRAINT chk_knowledge_item_version CHECK (version >= 1));
-- statement-break
CREATE INDEX idx_knowledge_items_retrieval ON knowledge_items(knowledge_base_id, status, visibility, effective_at);
-- statement-break
CREATE TABLE knowledge_images (id VARCHAR(191) PRIMARY KEY, knowledge_item_id VARCHAR(191) NOT NULL, storage_path VARCHAR(512) NOT NULL UNIQUE, mime_type VARCHAR(128) NOT NULL, width INTEGER NULL, height INTEGER NULL, metadata_json JSON NOT NULL, created_at VARCHAR(64) NOT NULL, CONSTRAINT fk_knowledge_image_item FOREIGN KEY (knowledge_item_id) REFERENCES knowledge_items(id) ON DELETE CASCADE, CONSTRAINT chk_knowledge_image_width CHECK (width IS NULL OR width > 0), CONSTRAINT chk_knowledge_image_height CHECK (height IS NULL OR height > 0));
-- statement-break
CREATE INDEX idx_knowledge_images_item ON knowledge_images(knowledge_item_id);
-- statement-break
CREATE TABLE knowledge_import_batches (id VARCHAR(191) PRIMARY KEY, knowledge_base_id VARCHAR(191) NOT NULL, file_name VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL, total_rows INTEGER NOT NULL, valid_rows INTEGER NOT NULL, invalid_rows INTEGER NOT NULL, created_by_user_id VARCHAR(191) NOT NULL, confirmed_by_user_id VARCHAR(191) NULL, created_at VARCHAR(64) NOT NULL, confirmed_at VARCHAR(64) NULL, updated_at VARCHAR(64) NOT NULL, CONSTRAINT fk_knowledge_batch_base FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id), CONSTRAINT chk_knowledge_batch_status CHECK (status IN ('previewed','confirmed','failed','cancelled')));
-- statement-break
CREATE TABLE knowledge_import_rows (id VARCHAR(191) PRIMARY KEY, batch_id VARCHAR(191) NOT NULL, row_number INTEGER NOT NULL, raw_data_json JSON NOT NULL, normalized_data_json JSON NOT NULL, status VARCHAR(32) NOT NULL, error_message TEXT NULL, knowledge_item_id VARCHAR(191) NULL, created_at VARCHAR(64) NOT NULL, CONSTRAINT fk_knowledge_import_row_batch FOREIGN KEY (batch_id) REFERENCES knowledge_import_batches(id) ON DELETE CASCADE, CONSTRAINT fk_knowledge_import_row_item FOREIGN KEY (knowledge_item_id) REFERENCES knowledge_items(id) ON DELETE SET NULL, CONSTRAINT uq_knowledge_import_row UNIQUE(batch_id, row_number), CONSTRAINT chk_knowledge_import_row_status CHECK (status IN ('valid','invalid','imported','duplicate')));
-- statement-break
INSERT INTO knowledge_bases (id, name, description, visibility, status, created_by_user_id, created_at, updated_at) SELECT 'learning-materials', 'Learning materials', 'Migrated learning resources', 'learner', 'enabled', 'system', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3) WHERE NOT EXISTS (SELECT 1 FROM knowledge_bases WHERE id = 'learning-materials');
-- statement-break
INSERT INTO knowledge_items (id, knowledge_base_id, title, summary, content, category, category_id, keywords_json, metadata_json, source_name, source_url, visibility, status, effective_at, withdrawn_at, previous_version_id, version, content_hash, embedding_status, created_by_user_id, created_at, updated_at) SELECT id, 'learning-materials', title, summary, content, resource_type, category_id, tags_json, JSON_OBJECT(), source_name, source_url, visibility, CASE status WHEN 'published' THEN 'published' WHEN 'withdrawn' THEN 'withdrawn' ELSE 'submitted' END, effective_at, withdrawn_at, previous_version_id, version, SHA2(CONCAT(id, title, content), 256), 'none', 'system', created_at, updated_at FROM learning_resources;
-- statement-break
ALTER TABLE learning_questions ADD COLUMN source_knowledge_item_id VARCHAR(191) NULL;
-- statement-break
UPDATE learning_questions SET source_knowledge_item_id = source_resource_id;
